name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      - name: Assemble
        run: ./gradlew assemble

  test-and-coverage:
    name: Test And Coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      - name: Run Tests
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tp4-reports
          path: |
            build/reports/tests/test/
            build/reports/jacoco/test/
